### ISSUE TITLE
review

### ISSUE THREAD

**Issue by kaat0** [gwehrle/Overpass.jl#2]
recommended:

- [x] include other OSs in CI.yml for testing, for example:
```
      matrix:
        version:
          - 'lts' # latest LTS build
          - '1' # current
          - 'pre' # latest prerelease build (RCs, betas, and alphas
        julia-arch: [x64, x86, aarch64]
        os: [macOS-latest, ubuntu-latest, windows-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86
          - os: ubuntu-latest
            julia-arch: aarch64
          - os: windows-latest
            julia-arch: aarch64
```
- [x] provide description for the different use of query() and turbo_url()

If helpful:

- [ ] Provide CRONTRIBUTION.md
- [x] use  all-contributors bot
